<?php

echo "Hello World !!";

//PERINTAH UNTUK ADD ATAU TAMBAH
//1. GIT ADD . ATAU GIT ADD NAMA_FOLDER/FILE
//PERINgiTAH UNTUK COMMIT ATAU KOMENTAR

//2. GIT COMMIT -M "KOMENTARNYA APA"
//PERINTAH UNTUK UPLOAD ATAU PUSH

//3. GIT PUSH -U ORIGIN MASTER
//PUSH ADALAH PERINTAH, ORIGIN ADALAH NAMA REMOTE
//MASTER ADALAH NAMA BRANCH

//INI MODIFY DARI SAYA DENGAN MENAMBAHKAN FILE BARU  

?>